### ISSUE TITLE
Items not saving in inventories of either base, player or storage

### ISSUE THREAD

**Issue by NekoDm** [SubnauticaNitrox/Nitrox#1003]
I have this issues that when ever I close the server and start the server all the item in the inventories even storage all disapear, for some reason only the repair tool are remain and other contrustion like mobile station contrustion are still remain

**Comment by TheClockTwister** [comment]
Which version do you use for playing?

**Comment by NekoDm** [comment]
> Which version do you use for playing?

I using the latest version of the nitrox and the latest version on subnautica on epic game

**Comment by NekoDm** [comment]
Also there are like some chunk load issues like the weack of the life pod 3 that should be there but, It GONE, and some mistery mushroom that have a signal on it, and avora explotion message reset when ever the server start again when loggin

**Comment by TheClockTwister** [comment]
Okay, a few questions left:
* which one is the "latest" version? Can you post the version at the bottom left corner in the Nitrox launcher please?
* Did you download the launcher or did you clone the repository and built it your own?
* how big is your world folder? Can you attatch your world data so I can have a look at it in-game?

**Comment by erios567** [comment]
I have the solution:
If a player that isn't the host leaves the game, all items disappear.
So if you want to close your world, you have to do it by shutting the server before anybody leaves!
(I think the Host can leave without problems)
interestingly the items don't seem to disappear if a player has a timeout, only if he leaves the server manually.
Seems like the game world memory kinda erases/closes itself without saving if someone presses "leave".

**Comment by NekoDm** [comment]
> Okay, a few questions left:
> 
> * which one is the "latest" version? Can you post the version at the bottom left corner in the Nitrox launcher please?
> * Did you download the launcher or did you clone the repository and built it your own?
> * how big is your world folder? Can you attatch your world data so I can have a look at it in-game?

**Comment by NekoDm** [comment]
> Okay, a few questions left:
> 
> * which one is the "latest" version? Can you post the version at the bottom left corner in the Nitrox launcher please?
> * Did you download the launcher or did you clone the repository and built it your own?
> * how big is your world folder? Can you attatch your world data so I can have a look at it in-game?

Nitrox and the subnautica all in latest version, and I download direct on the nitrox main website https://nitrox.rux.gg/
![image](https://user-images.githubusercontent.com/62012619/77991975-16839c00-7360-11ea-8a49-b80c92a641be.png)

World file is around 12.3MB 
![image](https://user-images.githubusercontent.com/62012619/77992048-3f0b9600-7360-11ea-9b97-b273a0292cdc.png)

we also found a tons of bugs like, base contruction always at 92% when relogin, player can still see each other contrustion builded but somehow it doesn't show what contruction that have been deleted by 1 person(litterally one person only who have decontruction can see it gone but other people can still see appearing there like nothing happen and still can used it making it super glitchy),some mystery invisible wall hitting the seamoth, or player disappear to other player when docking the seamoth on the moonpool

people can't stand in cyclops when someone driving it and shooting people out to the space

**Comment by TheClockTwister** [comment]
Thanks :) I think you should try what @erios567 mentioned and see if the inventories only get reset if a player leaves prior to server shutdown or if it's mre or less random. If he is right, and we know how we can easily reproduce this bug, we can find its cause much faster... Additionally, you could attatch a zip file of your world folder so we can experiment with your world, if it doesn't work with a fresh one...

**Comment by brianpopow** [comment]
i had the same issue playing with a friend yesterday. It seems this happens when a player disconnects unexpected. We had some connection issues.

This can be reproduced with just pressing alt+F4 during gameplay. I tried to find the reason, but i have no experience with unity and this mod source code. What i could find is, that `ItemContainerRemovePacketProcessor`  will be called when dropping out of the game unexpected and then `inventoryManager.ItemRemoved`  will be called for all items of that player.

Hope that helps someone with more experience then me to figure out whats going on.

**Comment by Patrik2212** [comment]
Same thing kinda happened to me and my friend, we were playing for 5 hours straight, logged out and everything was saved, logged back in to check in on the save and we had all our stuff and all cool, but the radio signals were missing, missions were stuck. So i started a new world, tried to stop the server before exiting the game to see if it's gonna work that way, but the same thing happens, equips and mats are there but there's no radio signals, no missions and it seems like the character is stuck on spawn, since there's no radio to repair since it was already done, but the server expects you to do it, therefore not giving new missions until the radio is repaired. Not sure what to do, try? Any help would be appriciated. I will upload my world for devs to try and work it out.
https://safenote.co/r/5e8935b59ce847@30741810
Thanks in advance

**Comment by brianpopow** [comment]
@Patrik2212 how is that the same thing? The original author talks about loosing his inventory items and you are talking about loosing story progress.

**Comment by Patrik2212** [comment]
Thought in a way of losing stuff, aka progress, but alrighty... lol

**Comment by Jannify** [comment]
Probably fixed with https://github.com/SubnauticaNitrox/Nitrox/pull/1118

**Comment by TimG233** [comment]
This issue still happens now. When reopening the server and game, some locker clears all items entirely. Also, some structure like ladder might also disappear. The poster on the wall is also missing. lifepod is missing (3 and 6 for host). Nitrox version: 1.6.1.0; Latest subnautica from Steam

**Comment by Reformer3990** [comment]
Still relevant today. Items are not saving inside seamoth storage when its on left side of seamoth, have yet to try other side or on prawnsuit.
