### ISSUE TITLE
All batteries used in items restore to 100% on server restart / turn on

### ISSUE THREAD

**Issue by RazzyFFA** [SubnauticaNitrox/Nitrox#1391]
### Version
 ALPHA V1.4.0.0

### Bug
 Every time the server gets restarted or turned back on after being offline, all the batteries in tools (e.g seaglide, repair tool) they get reset to 100% charge.

### Expected
 The expected behaviour of this should've been that the batteries would keep their current state of charge.

### Steps to reproduce
 It's very simple to do. Simply just consume some of the battery power of a random tool, until it goes below 99%. After that, either turn off the server and turn it back on, or just use the restart command to restart the server. Once you rejoin, your battery should have gone back to 100% charge.

### Other details:
 No extra details.
 No errors.
 No errors.

**Comment by Exso12Ecesis** [comment]
It also does not persist the battery type, if you insert an Ion battery or Lithium Battery, the battery will be reverted to a normal battery upon next server reload. I thought maybe #1370 would address this but it does not.

**Comment by RazzyFFA** [comment]
Yeah, it's very strange.

**Comment by Exso12Ecesis** [comment]
I looked through the issue backlog for more than a few seconds and keyword searching, and found there are several tickets that show the devs are already aware of this issue. More specifically, #1338 and #112. It's clear the devs are aware of all the issues we've recently posted, this seems to be apart of a larger issue of NitroX not persisting the metadata of the entities, which is probably why they stopped responding to spefific bug tickets like ours, something like this is low priority compared to functional and integration enhancements.

**Comment by RazzyFFA** [comment]
Ah I see, I guess that's fair on the dev's side.

**Comment by Jannify** [comment]
I am sure this is fixed by now

**Comment by RazzyFFA** [comment]
> I am sure this is fixed by now

Actually, it's not fixed. The bug still occurs to this very day on version v1.6.0.0.

**Comment by RazzyFFA** [comment]
> I checked this on the current master and there the battery charge persisted after a server restart.

Thats quite strange, I don't know if this is a bug that occurs over time, however something that I did not mention is that the batteries must be in items, also in the toolbar and not in the inventory. Something that I did find however is that the tools with batteries that remained in the inventory did keep their charge, however the ones in the toolbar reset to 100%.
