### ISSUE TITLE
Subnautica coop mod

### ISSUE THREAD

**Issue by Nycks** [SubnauticaNitrox/Nitrox#326]
i have installed subnautica from Epic games and i have this error when i start the nitrox server:
Nitrox] I: It appears you don't have Subnautica installed anywhere. The game files are needed to run the server.
[Nitrox] E: System.IO.FileNotFoundException: Make sure resources.assets is in current or parent directory and readable.

**Comment by TheNikoWTF** [comment]
Same here :|

**Comment by deathisnear24** [comment]
So I think I found a bandaid fix. I noticed the "Make sure resources.assets is in current or parent directory and readable.". I took the 'resources.assets' from my subnautica install folder (Subnautica\Subnautica_Data) and put it into Documents\Nitrox\NitroxServer\bin\Debug_WPF. It appears to work so far. I was able to join my own server, which I wasn't able to do before I copied that file to the Nitrox Folder. I will have to see later if my friends are able to join.

**Comment by TheNikoWTF** [comment]
I did that but the sync was really really really bad. I saw too, that the world was empty (no resources/animals etc) and the "It appears you don't have Subnautica installed anywhere." continues spaming the log

**Comment by deathisnear24** [comment]
Ahhh. I get the same thing. I get the spamming of "It appears you don't have Subnautica installed anywhere." Also no resources don't seem to appear as well as animals. I'm going to try copying the install files into my steam directory and see if that helps with just making it think I installed it there

**Comment by crankineer** [comment]
Hey so I just saw this thread and I'm having similar problems. I can't even get the Visual Studio part to work. It keeps saying stuff like "missing xml comment" or that it can't open the .sln file. Am I supposed to install all the plugins for Visual Studio?

**Comment by niceecin** [comment]
Nitrox hasn't yet been updated for install locations outside of your Steam library, but you can just save over the SteamHelper.cs class and circumvent the entire steam process. FindSubnauticaPath() is used to get the directory so you can replace the return statement with 
`return Optional<string>.Of("C:/your/game/directory");`
and it doesn't give you messages about not owning the game.

**Comment by Sajgoniarz** [comment]
I used Epic version too, and i fixed issue with steam location yesterday, but world is still empty. @TheNikoWTF how did you manage to fi creature spawning, since your link leads nowhere?

**Comment by Hawkiinz** [comment]
I tried to put my Subnautica installation folder but it still not working. I done something wrong ?

![github](https://user-images.githubusercontent.com/45894451/50041547-166e6880-0057-11e9-8202-a6c734755ae8.PNG)

**Comment by niceecin** [comment]
@TheNikoWTF Whatever comment you are trying to link to on issue 188 is gone. No one can see anything by clicking on that link.

**Comment by TheNikoWTF** [comment]
> @TheNikoWTF Whatever comment you are trying to link to on issue 188 is gone. No one can see anything by clicking on that link.

Copy it manually, i dont know why but dont work if you click it ^^

https://github.com/SubnauticaNitrox/Nitrox/issues/188#issuecomment-370823042

**Comment by Hawkiinz** [comment]
@TheNikoWTF i tried but it's not working. Nitrox server told me that Subnautica isn't install.
first file :
![first](https://user-images.githubusercontent.com/45894451/50042156-964d0080-0060-11e9-86cb-cb54cc268f49.PNG)

second file : 
![second](https://user-images.githubusercontent.com/45894451/50042177-d0b69d80-0060-11e9-8f44-1196487b740b.PNG)

**Comment by Hawkiinz** [comment]
Np, i will wait for a new version or a good fix

**Comment by plun92** [comment]
hi hi you can tell me how to install the nitrox mod on the launcher epic games pls?

**Comment by Sajgoniarz** [comment]
Well i have same issue in Steam and Epic version ;/

**Comment by GabrielBosco** [comment]
> @TheNikoWTF i tried but it's not working. Nitrox server told me that Subnautica isn't install.
> first file :
> ![first](https://user-images.githubusercontent.com/45894451/50042156-964d0080-0060-11e9-86cb-cb54cc268f49.PNG)
> 
> second file :
> ![second](https://user-images.githubusercontent.com/45894451/50042177-d0b69d80-0060-11e9-8f44-1196487b740b.PNG)

see,  string subnauticaPath = "D:/Program Files/Epic Games/Subnautica/"   it's missing ;
